### ISSUE TITLE
Installing Requirements fails on El Capitan due to Six

### ISSUE THREAD

**Issue by mindheist** [mozilla/Addon-Tests#849]
``` 

black-pearl:Addon-Tests
$ sudo pip install -Ur requirements.txt
The directory '/Users/prabhuhari/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/prabhuhari/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting fxapom==1.7.1 (from -r requirements.txt (line 1))
  Downloading fxapom-1.7.1-py2-none-any.whl
Collecting pyjwt==1.4.0 (from -r requirements.txt (line 2))
  Downloading PyJWT-1.4.0-py2.py3-none-any.whl
Collecting pytest==2.9.1 (from -r requirements.txt (line 3))
  Downloading pytest-2.9.1-py2.py3-none-any.whl (161kB)
    100% |████████████████████████████████| 163kB 696kB/s
Collecting pytest-selenium (from -r requirements.txt (line 4))
  Downloading pytest_selenium-1.2.1-py2-none-any.whl
Collecting pytest-variables (from -r requirements.txt (line 5))
  Downloading pytest_variables-1.4-py2-none-any.whl
Collecting pytest-xdist==1.14 (from -r requirements.txt (line 6))
  Downloading pytest_xdist-1.14-py2.py3-none-any.whl
Collecting pytz==2016.3 (from -r requirements.txt (line 7))
  Downloading pytz-2016.3-py2.py3-none-any.whl (479kB)
    100% |████████████████████████████████| 481kB 467kB/s
Requirement already up-to-date: requests==2.9.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 8))
Collecting PyFxA==0.0.8 (from fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading PyFxA-0.0.8.zip (41kB)
    100% |████████████████████████████████| 51kB 1.1MB/s
Collecting py>=1.4.29 (from pytest==2.9.1->-r requirements.txt (line 3))
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 92kB 1.3MB/s
Collecting pytest-html>=1.7 (from pytest-selenium->-r requirements.txt (line 4))
  Downloading pytest_html-1.8.0-py2.py3-none-any.whl
Requirement already up-to-date: selenium>=2.26.0 in /Library/Python/2.7/site-packages (from pytest-selenium->-r requirements.txt (line 4))
Collecting execnet>=1.1 (from pytest-xdist==1.14->-r requirements.txt (line 6))
  Downloading execnet-1.4.1-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 915kB/s
Collecting cryptography (from PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading cryptography-1.3.1-cp27-cp27m-macosx_10_10_intel.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 413kB/s
Collecting PyBrowserID (from PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading PyBrowserID-0.10.0.tar.gz
Collecting hawkauthlib (from PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading hawkauthlib-0.1.1.tar.gz
Collecting six (from PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting apipkg>=1.4 (from execnet>=1.1->pytest-xdist==1.14->-r requirements.txt (line 6))
  Downloading apipkg-1.4-py2.py3-none-any.whl
Requirement already up-to-date: setuptools>=11.3 in /Library/Python/2.7/site-packages/setuptools-20.9.0-py2.7.egg (from cryptography->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
Requirement already up-to-date: enum34 in /Library/Python/2.7/site-packages (from cryptography->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
Requirement already up-to-date: ipaddress in /Library/Python/2.7/site-packages (from cryptography->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
Requirement already up-to-date: pyasn1>=0.1.8 in /Library/Python/2.7/site-packages (from cryptography->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
Collecting idna>=2.0 (from cryptography->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading idna-2.1-py2-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 2.6MB/s
Collecting cffi>=1.4.1 (from cryptography->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading cffi-1.6.0-cp27-cp27m-macosx_10_10_intel.whl (211kB)
    100% |████████████████████████████████| 215kB 1.5MB/s
Collecting webob (from hawkauthlib->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading WebOb-1.6.0-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 1.9MB/s
Collecting pycparser (from cffi>=1.4.1->cryptography->PyFxA==0.0.8->fxapom==1.7.1->-r requirements.txt (line 1))
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 1.5MB/s
Installing collected packages: six, idna, pycparser, cffi, cryptography, PyBrowserID, webob, hawkauthlib, PyFxA, fxapom, pyjwt, py, pytest, pytest-html, pytest-variables, pytest-selenium, apipkg, execnet, pytest-xdist, pytz
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-tcQXa5-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

```

**Comment by mindheist** [comment]
this seems to be a bug in pip though ( https://github.com/pypa/pip/issues/3165 ) , and looks like apple is installing an older version of six by default . for now I m using 

```  sudo pip install -Ur requirements.txt --ignore-installed six ``` 

Please LMK if this might lead to some other dependency issues.

**Comment by davehunt** [comment]
Please try installing dependencies into a [virtual environment](https://virtualenv.pypa.io/en/latest/) rather than your default site packages. This will allow you to have only the versions required for the project and keeps your default site packages clean.
